### ISSUE TITLE
隐藏滚动条

### ISSUE THREAD

**Issue by hocgin** [hocgin/chrome-extension-weather#9]
Chrome Version: 
OS:  WIN
=========
```css
::-webkit-scrollbar {
    display: NONE;
}
```
